name: Build and Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --no-build --configuration Release

      - name: Extract Version
        id: vars
        run: echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Pack
        run: dotnet pack loxone-link-dotnet/loxone-link-dotnet.csproj --no-build --configuration Release -p:PackageVersion=${{ steps.vars.outputs.version }} -o ./out

      - name: Push to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push ./out/*.nupkg --api-key "$NUGET_API_KEY" --source https://api.nuget.org/v3/index.json